services:
  postgres:
    image: postgres:15
    container_name: chatbot_postgres
    restart: always
    environment:
      POSTGRES_USER: teuzo
      POSTGRES_PASSWORD: teuzo123
      POSTGRES_DB: chatbotdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: chatbot_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: teuzo
      MONGO_INITDB_ROOT_PASSWORD: teuzo123
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
